apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace/namespace.yaml
  - rbac/monitoring-rbac.yaml
  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - loki/configmap.yaml
  - loki/deployment.yaml
  - loki/service.yaml
  - tempo/configmap.yaml
  - tempo/deployment.yaml
  - tempo/service.yaml
  - grafana/sealed-secret.yaml
  - grafana/datasources.yaml
  - grafana/alerting.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - alloy/configmap.yaml
  - alloy/daemonset.yaml
  - alloy/service.yaml
