apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:13.0.1-security-01
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: admin-password
                  optional: true
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
          envFrom:
            - secretRef:
                name: grafana-smtp
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: alerting
              mountPath: /etc/grafana/provisioning/alerting
            - name: dashboard-providers
              mountPath: /etc/grafana/provisioning/dashboards
            - name: kubernetes-dashboards
              mountPath: /var/lib/grafana/dashboards/kubernetes
            - name: data
              mountPath: /var/lib/grafana
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: alerting
          configMap:
            name: grafana-alerting
        - name: dashboard-providers
          configMap:
            name: grafana-dashboard-providers
        - name: kubernetes-dashboards
          configMap:
            name: grafana-kubernetes-platform-dashboard
        - name: data
          emptyDir: {}
